# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-14 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.TextField(default='null'),
        ),
    ]
